#!/usr/bin/env bash
set -o nounset -o errexit -o errtrace -o pipefail

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")

# shellcheck source=../../../scripts/lib/bash-tap
source "${SCRIPT_DIR}"/../../../scripts/lib/bash-tap
TODO= # Define here to prevent unbound variable error from bash-tap.

function compare_qpc_dac_fetch_all_detailed_connections_and_qpc_dac_ls_detailed_connections() {
  echo "# ##########"
  echo "# compare_qpc_dac_fetch_all_connections_and_qpc_dac_ls_connections"
  echo "# "
  qpc dac fetch-all detailed-connections >/tmp/qpc_dac_fetch_all_detailed_connections.$$
  qpc dac ls detailed-connections >/tmp/qpc_dac_ls_detailed_connections.$$
  if diff /tmp/qpc_dac_fetch_all_detailed_connections.$$ /tmp/qpc_dac_ls_detailed_connections.$$ |
    sed 's/^/# /'; then
    ok 1 "qpc dac fetch-all detailed-connections and qpc dac ls detailed-connections are the same."
  else
    ok 0 "qpc dac fetch-all detailed-connections and qpc dac ls detailed-connections are different."
  fi
  # Clean up temporary files
  rm -f /tmp/qpc_dac_fetch_all_detailed_connections.$$ /tmp/qpc_dac_ls_detailed_connections.$$
}

function main() {
  local num_of_tests=4
  plan tests ${num_of_tests}

  local top_dir basename
  top_dir=$(realpath "${SCRIPT_DIR}"/../)
  ok 1 "Detected top_dir=${top_dir}"

  basename=$(basename "${top_dir}")
  ok 1 "Detected basename=${basename}"

  pushd "${top_dir}" &>/dev/null
  is "$(pwd)" "${top_dir}" "I just changed the current working directory to ${top_dir}."

  export PATH=.:${PATH}
  compare_qpc_dac_fetch_all_detailed_connections_and_qpc_dac_ls_detailed_connections

  popd &>/dev/null

  done_testing ${num_of_tests}
}

main "$@"
