#!/usr/bin/env bash
set -o nounset -o errexit -o errtrace -o pipefail

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")

# shellcheck source=../../../scripts/lib/bash-tap
source "${SCRIPT_DIR}"/../../../scripts/lib/bash-tap
TODO= # Define here to prevent unbound variable error from bash-tap.

function compare_qpc_dac_sensitive_data_rule_fetch_and_list_1() {
  echo "# ##########"
  echo "# compare_qpc_dac_sensitive_data_rule_fetch_and_list_1"
  echo "# "
  qpc dac sensitive-data-rule fetch >/tmp/qpc_dac_sensitive_data_rule_fetch.$$ 2>&1 || true
  qpc dac sensitive-data-rule ls >/tmp/qpc_dac_sensitive_data_rule_list.$$ 2>&1 || true
  if diff /tmp/qpc_dac_sensitive_data_rule_fetch.$$ /tmp/qpc_dac_sensitive_data_rule_list.$$ |
    sed 's/^/# /'; then
    ok 1 "\`qpc dac sensitive-data-rule fetch\` and \`qpc dac sensitive-data-rule ls\` are the same."
  else
    ok 0 "\`qpc dac sensitive-data-rule fetch\` and \`qpc dac sensitive-data-rule ls\` are different."
  fi
  # Clean up temporary files
  rm -f /tmp/qpc_dac_sensitive_data_rule_fetch.$$ /tmp/qpc_dac_sensitive_data_rule_list.$$
}

function main() {
  local num_of_tests=4
  plan tests ${num_of_tests}

  local top_dir basename
  top_dir=$(realpath "${SCRIPT_DIR}"/../)
  ok 1 "Detected top_dir=${top_dir}"

  basename=$(basename "${top_dir}")
  ok 1 "Detected basename=${basename}"

  pushd "${top_dir}" &>/dev/null
  is "$(pwd)" "${top_dir}" "I just changed the current working directory to ${top_dir}."

  export PATH=.:${PATH}
  compare_qpc_dac_sensitive_data_rule_fetch_and_list_1

  popd &>/dev/null

  done_testing ${num_of_tests}
}

main "$@"
