#!/usr/bin/env bash
set -o nounset -o errexit -o errtrace -o pipefail

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")

# shellcheck source=../../../scripts/lib/bash-tap
source "${SCRIPT_DIR}"/../../../scripts/lib/bash-tap
TODO= # Define here to prevent unbound variable error from bash-tap.

function test_qpc_exists() {
  local qpc
  qpc=$(command -v qpc || true)
  like "${qpc}" "/qpc$" "It should find \`qpc\` at \`${qpc}\`."
}

function test_qpc_user() {
  echo "# ##########"
  echo "# test_qpc_user"
  echo "# "

  local actual_header expected actual
  actual_header=$(qpc user | head -1 || true)
  is "${actual_header}" "Manage user accounts with QueryPie API v2" \
    "It should print a header line, Manage user accounts with QueryPie API v2."

  expected="Available Commands:
  fetch-all   Fetch all users from QueryPie server and save them to local sqlite database
  ls          List all users in local sqlite database

Flags:"
  actual=$(qpc user | grep --after-context=4 "Available Command")
  is "${actual}" "${expected}" "It should print available commands."
}

function test_qpc_user_fetch_all() {
  local actual_header actual_output
  echo "# ##########"
  echo "# test_qpc_user_fetch_all"
  echo "# "

  actual_header=$(qpc user fetch-all | head -1 || true)
  like "${actual_header}" "^UUID * LOGIN_ID * EMAIL * NAME * STATUS * MORE * CREATED * UPDATED *$" \
    "It should print a header line of UUID, LOGIN_ID, EMAIL, NAME, STATUS, MORE, CREATED, UPDATED."

  actual_output=$(qpc user fetch-all | grep brant | sed 's/   */\t/g' || true)
  IFS=$'\t'
  read -r UUID LOGIN_ID EMAIL NAME STATUS MORE CREATED UPDATED <<< "${actual_output}"

  like "${UUID}" "^[0-9a-f\-]{36}$" \
    "It should print output of brant which UUID is an unspecified value."
  is "${LOGIN_ID}" "brant@chequer.io" \
    "It should print output of brant which LOGIN_ID is an email address."
  is "${EMAIL}" "brant@chequer.io" \
    "It should print output of brant which EMAIL is an email address."
  is "${NAME}" "Brant Hwang" \
    "It should print output of brant which NAME is Brant Hwang."
  is "${STATUS}" "ACTIVE" \
    "It should print output of brant which STATUS is ACTIVE."
  is "${MORE}" "-" \
    "It should print output of brant which MORE is -."
  like "${CREATED}" "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}$" \
    "It should print output of brant which CREATED is yyyy-mm-dd HH:MM."
  like "${UPDATED}" "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}$" \
    "It should print output of brant which UPDATED is yyyy-mm-dd HH:MM."
}

function test_qpc_user_ls() {
  local actual_header actual_output
  echo "# ##########"
  echo "# test_qpc_user_ls"
  echo "# "

  actual_header=$(qpc user ls | head -1 || true)
  like "${actual_header}" "^UUID * LOGIN_ID * EMAIL * NAME * STATUS * MORE * CREATED * UPDATED *$" \
    "It should print a header line of UUID, LOGIN_ID, EMAIL, NAME, STATUS, MORE, CREATED, UPDATED."

  actual_output=$(qpc user ls | grep brant | sed 's/   */\t/g' || true)
  IFS=$'\t'
  read -r UUID LOGIN_ID EMAIL NAME STATUS MORE CREATED UPDATED <<< "${actual_output}"

  like "${UUID}" "^[0-9a-f\-]{36}$" \
    "It should print output of brant which UUID is an unspecified value."
  is "${LOGIN_ID}" "brant@chequer.io" \
    "It should print output of brant which LOGIN_ID is an email address."
  is "${EMAIL}" "brant@chequer.io" \
    "It should print output of brant which EMAIL is an email address."
  is "${NAME}" "Brant Hwang" \
    "It should print output of brant which NAME is Brant Hwang."
  is "${STATUS}" "ACTIVE" \
    "It should print output of brant which STATUS is ACTIVE."
  is "${MORE}" "-" \
    "It should print output of brant which MORE is -."
  like "${CREATED}" "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}$" \
    "It should print output of brant which CREATED is yyyy-mm-dd HH:MM."
  like "${UPDATED}" "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}$" \
    "It should print output of brant which UPDATED is yyyy-mm-dd HH:MM."
}

function compare_qpc_user_fetch_all_and_qpc_user_ls() {
  echo "# ##########"
  echo "# compare_qpc_user_fetch_all_and_qpc_user_ls"
  echo "# "
  qpc user fetch-all >/tmp/qpc_user_fetch_all.$$ 2>&1
  qpc user ls >/tmp/qpc_user_ls.$$ 2>&1
  if diff /tmp/qpc_user_fetch_all.$$ /tmp/qpc_user_ls.$$ |
    sed 's/^/# /'; then
    ok 1 "\`qpc user fetch-all\` and \`qpc user ls\` are the same."
  else
    ok 0 "\`qpc user fetch-all\` and \`qpc user ls\` are different."
  fi
  # Clean up temporary files
  rm -f /tmp/qpc_user_fetch_all.$$ /tmp/qpc_user_ls.$$
}

function main() {
  local num_of_tests=25
  plan tests ${num_of_tests}

  local top_dir basename
  top_dir=$(realpath "${SCRIPT_DIR}"/../)
  ok 1 "Detected top_dir=${top_dir}"

  basename=$(basename "${top_dir}")
  ok 1 "Detected basename=${basename}"

  pushd "${top_dir}" &>/dev/null
  is "$(pwd)" "${top_dir}" "I just changed the current working directory to ${top_dir}."

  export PATH=.:${PATH}
  test_qpc_exists
  test_qpc_user
  test_qpc_user_fetch_all
  test_qpc_user_ls
  compare_qpc_user_fetch_all_and_qpc_user_ls

  popd &>/dev/null

  done_testing ${num_of_tests}
}

main "$@"
